[The truth](https://www.tweag.io/blog/2020-04-16-exceptions-in-haskell/#fnref-2) of the matter is that throwing exceptions was never a problem for purity: the problem was catching exceptions
